# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

stages:
- stage: Build_And_Push_image
  displayName: Build & Push image
  jobs:
  - job: Build_And_Push
    displayName: Build & Push
    pool:
      vmImage: ubuntu-latest
    steps:   
    - task: Docker@2.211.0
      displayName: Build & Push an image
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'baneeishaque/gp-vnc-as-chr-idea-charm-cond3-mine-r-matlab-mysql-phpwebst-1366x625-code-asdf-flutter-jadx-rclone'
        command: 'buildAndPush'
        Dockerfile: '.gitpod.Dockerfile'
        tags: 'latest'